### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by krasa** [krasa/CpuUsageIndicator#2]
```
HDC for component
java.lang.NullPointerException: HDC for component
                at sun.java2d.loops.MaskBlit.MaskBlit(Native Method)
                at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
                at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
                at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
                at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
                at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
                at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
                at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
                at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
                at com.intellij.util.ui.UIUtil.drawImage(UIUtil.java:1887)
                at com.intellij.util.ui.UIUtil.drawImage(UIUtil.java:1866)
                at krasa.cpu.CpuUsagePanel.draw(CpuUsagePanel.java:193)
                at krasa.cpu.CpuUsagePanel.paintComponent(CpuUsagePanel.java:186)
                at krasa.cpu.CpuUsagePanel.update(CpuUsagePanel.java:240)
                at krasa.cpu.CpuUsageManager.update(CpuUsageManager.java:35)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
                at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:239)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
```

**Comment by krasa** [comment]
```
Width (0) and height (0) cannot be <= 0
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at com.intellij.util.ui.UIUtil.createImage(UIUtil.java:1938)
	at krasa.cpu.CpuUsagePanel.paintComponent(CpuUsagePanel.java:134)
	at krasa.cpu.CpuUsagePanel.update(CpuUsagePanel.java:240)
	at krasa.cpu.CpuUsageManager.update(CpuUsageManager.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
