### ISSUE TITLE
Crash while starting CLion Build #CL-231.8109.174, built on March 28, 2023

### ISSUE THREAD

**Issue by cdannebe** [krasa/CpuUsageIndicator#7]
Hi, I had a crash while starting the CLion.

Stack Trace:

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at com.intellij.util.ui.ImageUtil.createImage(ImageUtil.java:107)
	at com.intellij.util.ui.ImageUtil.createImage(ImageUtil.java:93)
	at krasa.cpu.CpuUsagePanel.paintComponent(CpuUsagePanel.java:185)
	at krasa.cpu.CpuUsagePanel.update(CpuUsagePanel.java:293)
	at krasa.cpu.CpuUsageManager.update(CpuUsageManager.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by krasa** [comment]
Thanks :-)
